name: Compress images

on:
  pull_request:
    paths:
      - 'src/assets/**'
  push:
    branches: [main]
    paths:
      - 'src/assets/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: false
          jpegQuality: 85
          pngQuality: 85
          webpQuality: 85
